# Generated by Django 4.2.28 on 2026-07-24 02:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_alter_empleado_options_empleado_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=75)),
                ('segundo_nombre', models.CharField(blank=True, max_length=75)),
                ('primer_apellido', models.CharField(max_length=75)),
                ('segundo_apellido', models.CharField(blank=True, max_length=75)),
                ('fecha_nacimiento', models.DateField()),
                ('lugar_nacimiento', models.CharField(max_length=150)),
                ('tipo_identificacion', models.CharField(choices=[('IDENTIDAD', 'Identidad'), ('CARNET_RESIDENCIA', 'Carnet de Residencia'), ('PASAPORTE', 'Pasaporte')], default='IDENTIDAD', max_length=20)),
                ('numero_identificacion', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='No. de Identificación')),
                ('genero', models.CharField(choices=[('FEMENINO', 'Femenino'), ('MASCULINO', 'Masculino')], max_length=10)),
                ('nacionalidad', models.CharField(choices=[('HONDURENA', 'Hondureña'), ('EXTRANJERA', 'Extranjera')], max_length=15)),
                ('profesion_ocupacion_oficio', models.CharField(max_length=150, verbose_name='Profesión / Ocupación / Oficio')),
                ('telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('email_personal', models.EmailField(blank=True, max_length=254)),
                ('direccion_colonia_barrio', models.CharField(max_length=150, verbose_name='Colonia / Barrio / Aldea')),
                ('calle_avenida', models.CharField(max_length=150, verbose_name='Calle / Avenida')),
                ('numero_casa', models.CharField(blank=True, max_length=30, verbose_name='No. de Casa')),
                ('punto_referencia', models.CharField(blank=True, max_length=255)),
                ('municipio', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('pais', models.CharField(default='Honduras', max_length=100)),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('UNION_LIBRE', 'Unión libre')], max_length=15)),
                ('numero_dependientes', models.PositiveIntegerField(default=0)),
                ('nombre_conyuge', models.CharField(blank=True, max_length=150)),
                ('conyuge_telefono_fijo', models.CharField(blank=True, max_length=20)),
                ('conyuge_celular', models.CharField(blank=True, max_length=20)),
                ('conyuge_empresa', models.CharField(blank=True, max_length=150, verbose_name='Empresa donde labora el cónyuge')),
                ('ref1_nombre', models.CharField(max_length=150, verbose_name='Referencia 1 - Nombre completo')),
                ('ref1_telefono_fijo', models.CharField(blank=True, max_length=20, verbose_name='Referencia 1 - Teléfono fijo')),
                ('ref1_celular', models.CharField(max_length=20, verbose_name='Referencia 1 - Celular')),
                ('ref2_nombre', models.CharField(blank=True, max_length=150, verbose_name='Referencia 2 - Nombre completo')),
                ('ref2_telefono_fijo', models.CharField(blank=True, max_length=20, verbose_name='Referencia 2 - Teléfono fijo')),
                ('ref2_celular', models.CharField(blank=True, max_length=20, verbose_name='Referencia 2 - Celular')),
                ('tipo_empresa', models.CharField(choices=[('PRIVADA', 'Empresa privada'), ('PUBLICA', 'Empresa pública'), ('ONG', 'ONG')], max_length=15)),
                ('tipo_empleado', models.CharField(choices=[('INDEPENDIENTE', 'Profesional independiente'), ('PROPIETARIO', 'Propietario'), ('COMERCIANTE', 'Comerciante individual')], max_length=15)),
                ('empresa_nombre', models.CharField(max_length=150, verbose_name='Nombre de la empresa en la que labora')),
                ('empresa_fecha_ingreso', models.DateField()),
                ('empresa_anios_laborando', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')], verbose_name='Años laborando')),
                ('cargo_actual', models.CharField(max_length=100)),
                ('empresa_telefono', models.CharField(max_length=20)),
                ('empresa_email', models.EmailField(blank=True, max_length=254)),
                ('empresa_direccion', models.CharField(max_length=255)),
                ('empresa_ciudad', models.CharField(max_length=100)),
                ('empresa_municipio', models.CharField(max_length=100)),
                ('empresa_departamento', models.CharField(max_length=100)),
                ('gerente_rrhh_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Gerente / Jefe de Recursos Humanos')),
                ('jefe_inmediato_nombre', models.CharField(blank=True, max_length=150, verbose_name='Nombre del Jefe inmediato')),
                ('actividad_economica', models.CharField(blank=True, max_length=150, verbose_name='Actividad Económica / Negocio')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')], verbose_name='Ingreso Mensual')),
                ('rango_salario', models.CharField(choices=[('RANGO_1', 'L 0 – L 8,500.00'), ('RANGO_2', 'L 8,501.00 – L 26,500.00'), ('RANGO_3', 'L 26,501.00 – L 54,000.00'), ('RANGO_4', 'L 54,001.00 – L 108,000.00'), ('RANGO_5', 'L 108,001.00 – L 150,000.00'), ('RANGO_6', 'L 150,001.00 – L 200,000.00'), ('RANGO_7', 'L 200,001.00 en adelante')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='CuotaAmortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto_capital', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')])),
                ('monto_interes', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')])),
                ('monto_total_cuota', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')])),
                ('estado_cuota', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO_PARCIAL', 'Pagado Parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
            ],
            options={
                'verbose_name': 'Cuota de Amortización',
                'verbose_name_plural': 'Tabla de Amortización',
                'ordering': ['prestamo', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_credito', models.CharField(editable=False, max_length=20, unique=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')])),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')])),
                ('plazo_meses', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe ser al menos 1 mes.')])),
                ('frecuencia_pago', models.CharField(choices=[('SEMANAL', 'Semanal'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], default='MENSUAL', max_length=15)),
                ('destino', models.CharField(choices=[('MEJORAS', 'Mejoras'), ('PAGO_DEUDA', 'Pago de deuda'), ('COLEGIATURA', 'Pago de colegiatura'), ('GASTOS_MEDICOS', 'Gastos médicos'), ('CONSUMO', 'Consumo')], max_length=20, verbose_name='Destino del préstamo')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('DESEMBOLSADO', 'Desembolsado / Activo'), ('EN_MORA', 'En Mora'), ('LIQUIDADO', 'Liquidado / Pagado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_desembolso', models.DateTimeField(blank=True, null=True)),
                ('documento_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_aprobados', to='empleados.empleado')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_asesorados', to='empleados.empleado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='financiera.cliente')),
                ('desembolsado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos_desembolsados', to='empleados.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('PAGO_CUOTA', 'Pago de Cuota'), ('DESEMBOLSO', 'Desembolso'), ('AJUSTE', 'Ajuste')], max_length=15)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')])),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('numero_comprobante', models.CharField(blank=True, max_length=30, unique=True)),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='empleados.empleado')),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='financiera.cuotaamortizacion')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='financiera.prestamo')),
            ],
            options={
                'verbose_name': 'Transacción de Caja',
                'verbose_name_plural': 'Transacciones de Caja',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.AddField(
            model_name='cuotaamortizacion',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='financiera.prestamo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotaamortizacion',
            unique_together={('prestamo', 'numero_cuota')},
        ),
    ]
