# Generated by Django 4.2.28 on 2026-07-21 07:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa_anios_laborando',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')], verbose_name='Años laborando'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ingresos_mensuales',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')], verbose_name='Ingreso Mensual'),
        ),
        migrations.AlterField(
            model_name='cuotaamortizacion',
            name='monto_capital',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='cuotaamortizacion',
            name='monto_interes',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='cuotaamortizacion',
            name='monto_total_cuota',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='plazo_meses',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Debe ser al menos 1 mes.')]),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes_anual',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'), message='No puede ser negativo.')]),
        ),
        migrations.AlterField(
            model_name='transaccioncaja',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Debe ser mayor a cero.')]),
        ),
    ]
