# Generated by Django 4.2.28 on 2026-07-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='tipo_credito',
            field=models.CharField(choices=[('PERSONAL', 'Personal'), ('HIPOTECARIO', 'Hipotecario')], default='PERSONAL', max_length=15, verbose_name='Tipo de Crédito'),
        ),
    ]
