# Generated by Django 4.2.28 on 2026-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0003_pagare_saldo_cuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccioncaja',
            name='tipo_movimiento',
            field=models.CharField(choices=[('PAGO_CUOTA', 'Pago de Cuota'), ('DESEMBOLSO', 'Desembolso'), ('AJUSTE', 'Ajuste'), ('MORA', 'Mora'), ('ABONO_CAPITAL', 'Abono a Capital')], max_length=15),
        ),
    ]
