# Generated by Django 4.2.28 on 2026-07-25 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financiera', '0004_alter_transaccioncaja_tipo_movimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestamo',
            old_name='tasa_interes_anual',
            new_name='tasa_interes_mensual',
        ),
    ]
