# Generated by Django 4.2.28 on 2026-07-21 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Estado Activo'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('ASESOR', 'Asesor de Crédito'), ('ANALISTA', 'Analista de Crédito'), ('GERENTE', 'Gerente / Comité de Crédito'), ('CAJERO', 'Cajero'), ('ADMIN', 'Administrador del Sistema')], default='ASESOR', max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='empleado',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
